### ISSUE TITLE
Operator/operand type mismatch error

### ISSUE THREAD

**Issue by Terterola** [VFPX/FastXTab#3]
Hi there! 

I'm running [fastxtab 1.6](https://github.com/VFPX/FastXTab/tree/master/fastxtab%201.6) and I'm getting type mismatch error at the line just after [this weird one](https://github.com/VFPX/FastXTab/blob/19938e816c0c5e7793add16048b1fadae5cde6c2/fastxtab%201.6/fastxtab.PRG#L1287).

It seems the code in lines 7 to 9 bellow is misplaced (or am I missing something?)

```
1			for lnI = 1 to This.nMultiRowField
2				lcField = InpFields[This.anRowField[m.lnI], 1]
3				if This.nMultiRowField = 1
4					lcValue = rowfld
5				else
6					lcValue = evaluate('rowfld' + transform(lnI))
7				endif _This.nMultiRowField > 1
8				rowfldvalue = rowfldvalue + iif(empty(rowfldvalue), '', ',') + ;
9					lcValue
10				if lnI = 1
11					insert into (m.cOutStem) ((lcField)) values (lcValue)
12				else
13					replace (lcField) with lcValue in (m.cOutStem)
14				endif
15			next
```

Here is the bit of code I'm using to test Fastxtab:

```
Local oFastX As fastxtab
oFastX = NEWOBJECT('fastxtab',[fastxtab.prg])
With oFastX As fastxtab
   .cOuTFILE = [curTemp]
   .lCuRSORONLY = .T.
   .CROWFIELD = [user_id]   
   .cCOLFIELD = [YEAR(sale_date)]
   .cDATAFIELD = [total]        
   .runxtab()
Endwith
```

**Comment by DougHennig** [comment]
There's nothing wrong with that code; VFP ignores anything after the ENDIF so I typically add what was on the IF statement so I can see which IF this is the ENDIF for.

Trace the code and see what the value of lcValue is, what the value of lnI is, and what the value rowfldN is, where N is the value of lnI.

**Comment by Terterola** [comment]
Ok, Doug, got it working. First field should be a string and it was numeric. My fault. Feel free to delete my recent issues by mistake. Have a great new year!
